from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from okoffice.schemas.errors import OKofficeException
from okoffice.schemas.models import ToolManifest, ToolSpec

IMPLEMENTED_TOOLS = {
    "agent.setup.claude_code",
    "agent.setup.codex",
    "agent.setup.kilo_code",
    "agent.setup.openclaw",
    "office.inspect.file",
    "word.inspect.document",
    "word.validation.document",
    "word.review.style",
    "word.validation.metadata",
    "word.validation.accessibility",
    "word.create.document",
    "word.create.memo",
    "word.create.report",
    "word.extract.text",
    "word.extract.outline",
    "word.extract.comments",
    "word.extract.revisions",
    "word.extract.fields",
    "word.extract.styles",
    "word.patch.plan",
    "word.patch.apply",
    "sheet.inspect.workbook",
    "sheet.write.workbook",
    "sheet.extract.formulas",
    "sheet.extract.charts",
    "sheet.extract.named_ranges",
    "sheet.extract.comments",
    "sheet.extract.pivots",
    "sheet.validation.formulas",
    "sheet.validation.model_checks",
    "sheet.validation.external_links",
    "sheet.patch.cells",
    "sheet.patch.table",
    "sheet.patch.formulas",
    "sheet.patch.chart",
    "sheet.review.model",
    "sheet.review.number_consistency",
    "deck.inspect.presentation",
    "deck.extract.text",
    "deck.extract.notes",
    "deck.extract.shapes",
    "deck.extract.media",
    "deck.extract.charts",
    "deck.extract.theme",
    "deck.compose.plan",
    "deck.render.html",
    "deck.validation.html_preview",
    "deck.create.presentation",
    "deck.create.from_outline",
    "deck.patch.apply",
    "deck.validate.presentation",
    "deck.validation.contact_sheet",
    "deck.validation.presentation",
    "deck.review.story",
    "deck.review.claims",
    "deck.validation.notes",
    "deck.validation.placeholders",
    "deck.export.pptx",
    "office.context.build_packet",
    "office.extract.schema",
    "office.validation.package",
    "office.workflow.docset_to_sheet",
    "office.workflow.sheet_to_deck",
    "office.workflow.board_pack",
    "office.workers.status",
    "office.bundle.export",
    "office.bundle.verify",
    "pdf.artifacts.graph",
    "pdf.artifacts.manifest",
    "pdf.artifacts.source_map",
    "pdf.inspect.document",
    "pdf.inspect.pages",
    "pdf.inspect.health",
    "pdf.workflow.plan",
    "pdf.workflow.run",
    "pdf.workflow.report",
    "pdf.workflow.createpdf",
    "pdf.workflow.research_deck",
    "pdf.authoring.plan",
    "pdf.research.plan",
    "pdf.research.source_cards",
    "pdf.research.evidence_cards",
    "pdf.storyboard.plan",
    "pdf.pages.write",
    "pdf.design.tokens",
    "pdf.pages.revise",
    "pdf.create.html_package",
    "pdf.qa.visual_report",
    "pdf.context.ingest",
    "pdf.context.packet",
    "pdf.context.build_packet",
    "pdf.context.classify",
    "pdf.context.image_analyze",
    "pdf.context.code_snapshot",
    "pdf.context.data_profile",
    "pdf.context.web_capture",
    "pdf.compose.plan",
    "pdf.compose.from_context",
    "pdf.compose.render_ir",
    "pdf.compose.add_code_block",
    "pdf.compose.add_figure",
    "pdf.compose.add_table",
    "pdf.compose.add_appendix",
    "pdf.compose.add_citation",
    "pdf.compose.add_media_reference",
    "pdf.compose.add_slide",
    "pdf.target.profiles",
    "pdf.target.select_profile",
    "pdf.target.validate_profile",
    "pdf.evidence.map_sources",
    "pdf.evidence.cite_claims",
    "pdf.evidence.coverage_report",
    "pdf.evidence.context_packet_report",
    "pdf.artifacts.export_bundle",
    "pdf.artifacts.verify_bundle",
    "pdf.patch.plan",
    "pdf.patch.preview",
    "pdf.patch.apply",
    "pdf.patch.verify",
    "pdf.compare.semantic_diff",
    "pdf.compare.visual_diff",
    "pdf.compare.version_report",
    "pdf.organize.merge",
    "pdf.organize.split",
    "pdf.organize.extract_pages",
    "pdf.organize.remove_pages",
    "pdf.organize.rotate_pages",
    "pdf.organize.reorder_pages",
    "pdf.organize.insert_blank_pages",
    "pdf.organize.n_up",
    "pdf.organize.booklet",
    "pdf.optimize.compress",
    "pdf.optimize.repair",
    "pdf.optimize.remove_unused_objects",
    "pdf.optimize.subset_fonts",
    "pdf.optimize.to_pdfa",
    "pdf.optimize.validate_pdfa",
    "pdf.convert.image_to_pdf",
    "pdf.convert.html_to_pdf",
    "pdf.convert.url_to_pdf",
    "pdf.convert.docx_to_pdf",
    "pdf.convert.pptx_to_pdf",
    "pdf.convert.xlsx_to_pdf",
    "pdf.convert.markdown_to_pdf",
    "pdf.convert.text_to_pdf",
    "pdf.convert.extract_images",
    "pdf.convert.extract_fonts",
    "pdf.convert.pdf_to_images",
    "pdf.convert.pdf_to_text",
    "pdf.convert.pdf_to_html",
    "pdf.convert.pdf_to_docx",
    "pdf.convert.pdf_to_pptx",
    "pdf.convert.pdf_to_xlsx",
    "pdf.convert.pdf_to_json",
    "pdf.convert.pdf_to_markdown",
    "pdf.render.html_package",
    "pdf.edit.watermark",
    "pdf.edit.page_numbers",
    "pdf.edit.add_shape",
    "pdf.edit.underline",
    "pdf.edit.strikeout",
    "pdf.edit.freehand_draw",
    "pdf.edit.resize_pages",
    "pdf.edit.add_margin",
    "pdf.edit.underlay",
    "pdf.metadata.read",
    "pdf.metadata.update",
    "pdf.metadata.remove",
    "pdf.metadata.page_info",
    "pdf.metadata.update_outline",
    "pdf.validation.validate_output",
    "pdf.validation.page_count_check",
    "pdf.validation.render_check",
    "pdf.validation.blank_page_check",
    "pdf.validation.visual_diff",
    "pdf.validation.redaction_check",
    "pdf.forms.import_data",
    "pdf.forms.create",
    "pdf.forms.validate",
    "pdf.ocr_scan.ocr",
    "pdf.ocr_scan.searchable_pdf",
    "pdf.ocr_scan.despeckle",
    "pdf.ocr_scan.remove_existing_ocr",
    "pdf.ocr_scan.scan_to_pdf",
    "pdf.ocr_scan.multilingual_ocr",
    "pdf.security.protect",
    "pdf.security.unlock_authorized",
    "pdf.security.encrypt",
    "pdf.security.decrypt_authorized",
    "pdf.security.sign",
    "pdf.security.verify_signature",
    "pdf.security.remove_metadata",
    "pdf.security.malware_scan",
    "pdf.security.sanitize",
    "pdf.security.redact",
    "pdf.security.verify_redaction",
    "pdf.ai.parse.lite",
    "pdf.ai.parse.figures",
    "pdf.ai.parse.formulas",
    "pdf.ai.parse.charts",
    "pdf.ai.parse.references",
    "pdf.ai.create.from_prompt",
    "pdf.ai.create.template_preview",
    "pdf.ai.create.templates",
    "pdf.ai.create.template_packs",
    "pdf.ai.create.validate_template_pack",
    "pdf.ai.create.plan_template_pack",
    "pdf.ai.create.agent",
    "pdf.ai.create.from_template_pack",
    "pdf.ai.rag.ingest",
    "pdf.ai.rag.query",
    "pdf.ai.rag.search",
    "pdf.ai.rag.cite_answer",
    "pdf.ai.rag.chat",
    "pdf.ai.rag.export_report",
    "pdf.ai.rag.highlight_sources",
    "office.extract.claims",
    "office.extract.entities",
    "office.extract.obligations",
    "office.inspect.batch",
    "office.evidence.map_sources",
    "office.evidence.coverage",
    "office.context.classify",
    "office.evidence.verify_citations",
    "office.bundle.report",
    "office.validate.output",
    "office.patch.plan",
    "office.patch.preview",
    "office.patch.verify",
    "office.workflow.review_and_patch",
    "office.workflow.redaction_packet",
    "office.bundle.graph",
}


@lru_cache(maxsize=1)
def load_tool_manifest() -> ToolManifest:
    manifest_path = _repo_root() / "schemas" / "tool-manifest.full.json"
    if manifest_path.exists():
        raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        tools = [_tool_spec_from_raw(item) for item in raw.get("tools", [])]
        return ToolManifest(
            manifest_version=str(raw.get("manifest_version", "0.1")),
            tools=tools,
        )
    return _fallback_manifest()


def list_tools() -> list[ToolSpec]:
    return load_tool_manifest().tools


def get_tool(name: str) -> ToolSpec:
    for tool in list_tools():
        if tool.name == name:
            return tool
    raise OKofficeException("tool_not_implemented", f"Unknown tool: {name}")


def _tool_spec_from_raw(raw: dict[str, Any]) -> ToolSpec:
    name = str(raw["name"])
    return ToolSpec(
        name=name,
        status=raw["status"],
        description=raw["description"],
        category=raw.get("category"),
        interfaces=list(raw.get("interfaces", [])),
        input_schema=raw.get("input_schema"),
        output_schema=raw.get("output_schema"),
        implemented=name in IMPLEMENTED_TOOLS,
    )


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _fallback_manifest() -> ToolManifest:
    return ToolManifest(
        tools=[
            ToolSpec(
                name="agent.setup.claude_code",
                status="beta",
                description="Generate Claude Code MCP config for local OKoffice tools.",
                category="agent",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.inspect.document",
                status="stable",
                description="Inspect a PDF document.",
                category="inspect",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.inspect.pages",
                status="stable",
                description="Inspect page-level geometry, text, image, and render facts.",
                category="inspect",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.plan",
                status="beta",
                description="Plan a local-first agent PDF workflow.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.run",
                status="beta",
                description="Execute a local-first agent PDF workflow manifest.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.report",
                status="beta",
                description="Summarize workflow artifacts, warnings, and validation.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.createpdf",
                status="beta",
                description="Create a validated PDF through the local HTML-first workflow with QA, artifact lineage, and optional verified audit bundle export.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.research_deck",
                status="beta",
                description="Plan a local research-to-deck workflow.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.authoring.plan",
                status="beta",
                description="Choose the safest local source format for a requested PDF deliverable.",
                category="authoring",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.storyboard.plan",
                status="beta",
                description="Create a deterministic page-by-page storyboard.",
                category="authoring",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.pages.write",
                status="beta",
                description="Convert a storyboard into page JSON blocks.",
                category="authoring",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.create.html_package",
                status="beta",
                description="Write a self-contained local HTML/CSS source package from page JSON or raw HTML.",
                category="authoring",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.qa.visual_report",
                status="beta",
                description="Run visual QA checks over generated PDFs and authoring/raw HTML package manifests.",
                category="validation",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.research.plan",
                status="beta",
                description="Plan source gathering for an agent-authored PDF.",
                category="research",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.research.source_cards",
                status="beta",
                description="Normalize researched sources into source cards.",
                category="research",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.research.evidence_cards",
                status="beta",
                description="Turn source cards into evidence cards.",
                category="research",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.insights.synthesize",
                status="planned",
                description="Synthesize source-backed insights behind an explicit model boundary.",
                category="insights",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=False,
            ),
            ToolSpec(
                name="pdf.design.tokens",
                status="beta",
                description="Generate or select reusable design tokens.",
                category="authoring",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.pages.revise",
                status="beta",
                description="Revise generated page JSON while preserving source references.",
                category="authoring",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.context.ingest",
                status="beta",
                description="Register a local source as a normalized context item.",
                category="context",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.context.packet",
                status="beta",
                description="Build a reusable Context Packet from raw or pre-ingested context items.",
                category="context",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.context.build_packet",
                status="beta",
                description="Build a local Context Packet with source graph metadata.",
                category="context",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.context.classify",
                status="beta",
                description="Classify context items by type, role, local evidence, safety limits, likely block type, and target slots.",
                category="context",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.compose.from_context",
                status="beta",
                description="Compose a validated target PDF from a Context Packet and target profile.",
                category="compose",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.target.profiles",
                status="beta",
                description="List built-in target PDF profiles with layout slots and accepted block types.",
                category="target",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.target.validate_profile",
                status="beta",
                description="Validate a built-in or custom target PDF profile for agent composition.",
                category="target",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.evidence.map_sources",
                status="beta",
                description="Attach source refs to generated blocks or claims using local context evidence.",
                category="evidence",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.evidence.cite_claims",
                status="beta",
                description="Return local citations for claims using source refs and source-map evidence.",
                category="evidence",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.evidence.coverage_report",
                status="beta",
                description="Create an evidence coverage report from a composition artifact.",
                category="evidence",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.evidence.context_packet_report",
                status="beta",
                description="Create a validated PDF and JSON audit report from a Context Packet source graph.",
                category="evidence",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.artifacts.export_bundle",
                status="beta",
                description="Export local PDFs, manifests, source maps, and reports as a portable audit bundle.",
                category="artifacts",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.artifacts.verify_bundle",
                status="beta",
                description="Verify a portable audit bundle manifest, ZIP entries, and SHA-256 checksums.",
                category="artifacts",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.plan",
                status="beta",
                description="Create a structured non-mutating patch manifest for Markdown, code, table, image, slide, citation, media reference, source-map, template-layer, HTML-layer, and regenerate_block evidence.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.preview",
                status="beta",
                description="Preview patch effects and validation requirements.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.apply",
                status="beta",
                description="Apply a patch transaction and write a new PDF artifact.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.verify",
                status="beta",
                description="Verify a patched PDF against a patch manifest.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.merge",
                status="stable",
                description="Merge multiple PDFs.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.split",
                status="stable",
                description="Split or extract selected PDF pages.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.extract_pages",
                status="stable",
                description="Extract specific pages into a new PDF.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.remove_pages",
                status="stable",
                description="Remove selected pages.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.rotate_pages",
                status="stable",
                description="Rotate selected pages.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.reorder_pages",
                status="stable",
                description="Reorder pages in a PDF.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.insert_blank_pages",
                status="stable",
                description="Insert blank pages into a PDF.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.optimize.compress",
                status="stable",
                description="Compress PDF content streams and report file-size savings.",
                category="optimize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.optimize.repair",
                status="beta",
                description="Rewrite a parseable PDF to rebuild output structure.",
                category="optimize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.image_to_pdf",
                status="stable",
                description="Create a PDF from local image files.",
                category="convert_to_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.markdown_to_pdf",
                status="stable",
                description="Create a PDF from Markdown content.",
                category="convert_to_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.text_to_pdf",
                status="stable",
                description="Create a PDF from plain text content.",
                category="convert_to_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_images",
                status="stable",
                description="Render PDF pages to images.",
                category="convert",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.extract_images",
                status="stable",
                description="Extract embedded images from PDF pages.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_text",
                status="stable",
                description="Extract text from PDF pages.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_json",
                status="beta",
                description="Export local Document IR JSON from a PDF.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_markdown",
                status="beta",
                description="Export cited Markdown from local Document IR.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.edit.watermark",
                status="stable",
                description="Add a text watermark overlay.",
                category="edit",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.edit.page_numbers",
                status="stable",
                description="Add page number overlays.",
                category="edit",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.metadata.read",
                status="stable",
                description="Read document metadata.",
                category="metadata",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.metadata.update",
                status="stable",
                description="Update document metadata.",
                category="metadata",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.metadata.remove",
                status="stable",
                description="Remove document metadata.",
                category="metadata",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.validation.validate_output",
                status="stable",
                description="Validate generated PDF output.",
                category="validation",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.validation.render_check",
                status="stable",
                description="Render selected pages in memory to verify output renderability.",
                category="validation",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.validation.blank_page_check",
                status="stable",
                description="Detect blank pages with text-layer and render evidence.",
                category="validation",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.parse.lite",
                status="beta",
                description="Parse PDF text layer into local Document IR.",
                category="ai_parse",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.from_prompt",
                status="beta",
                description="Create a validated local PDF from a prompt and template.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.template_preview",
                status="beta",
                description="Generate and validate a local preview PDF for a creation template.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.templates",
                status="beta",
                description="List local PDF creation templates, style packs, and color keys.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.template_packs",
                status="beta",
                description="List local template packs for agent-created PDFs.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.validate_template_pack",
                status="beta",
                description="Validate a local template pack contract.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.plan_template_pack",
                status="beta",
                description="Plan a local template-pack PDF creation call from target and context evidence.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.agent",
                status="beta",
                description="Run the local create agent: plan, create, render-check, blank-check, and coverage.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.from_template_pack",
                status="beta",
                description="Create a validated local PDF from a template pack with source, slot routing, and optional HTML package evidence.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.ingest",
                status="beta",
                description="Build a local cited keyword index from a PDF.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.query",
                status="beta",
                description="Query a local PDF index with extractive citations.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.search",
                status="beta",
                description="Search a local PDF index with cited chunks.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.cite_answer",
                status="beta",
                description="Find page and bbox citations that support an answer.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.chat",
                status="beta",
                description="Ask a local PDF and return answer, citations, report, and highlights.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.highlight_sources",
                status="beta",
                description="Create a highlighted source PDF from local RAG citations.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.export_report",
                status="beta",
                description="Create a cited PDF report from a local RAG answer.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
        ]
    )
