from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from agentpdf.schemas.errors import AgentPDFException
from agentpdf.schemas.models import ToolManifest, ToolSpec

IMPLEMENTED_TOOLS = {
    "agent.setup.claude_code",
    "pdf.inspect.document",
    "pdf.inspect.pages",
    "pdf.workflow.plan",
    "pdf.workflow.run",
    "pdf.workflow.report",
    "pdf.context.build_packet",
    "pdf.compose.from_context",
    "pdf.target.profiles",
    "pdf.target.validate_profile",
    "pdf.evidence.coverage_report",
    "pdf.artifacts.export_bundle",
    "pdf.artifacts.verify_bundle",
    "pdf.patch.plan",
    "pdf.patch.preview",
    "pdf.patch.apply",
    "pdf.patch.verify",
    "pdf.organize.merge",
    "pdf.organize.split",
    "pdf.organize.extract_pages",
    "pdf.organize.remove_pages",
    "pdf.organize.rotate_pages",
    "pdf.organize.reorder_pages",
    "pdf.organize.insert_blank_pages",
    "pdf.optimize.compress",
    "pdf.optimize.repair",
    "pdf.convert.image_to_pdf",
    "pdf.convert.markdown_to_pdf",
    "pdf.convert.text_to_pdf",
    "pdf.convert.extract_images",
    "pdf.convert.pdf_to_images",
    "pdf.convert.pdf_to_text",
    "pdf.convert.pdf_to_json",
    "pdf.convert.pdf_to_markdown",
    "pdf.edit.watermark",
    "pdf.edit.page_numbers",
    "pdf.metadata.read",
    "pdf.metadata.update",
    "pdf.metadata.remove",
    "pdf.validation.validate_output",
    "pdf.validation.render_check",
    "pdf.validation.blank_page_check",
    "pdf.ai.parse.lite",
    "pdf.ai.create.from_prompt",
    "pdf.ai.create.template_preview",
    "pdf.ai.create.templates",
    "pdf.ai.create.template_packs",
    "pdf.ai.create.validate_template_pack",
    "pdf.ai.create.plan_template_pack",
    "pdf.ai.create.agent",
    "pdf.ai.create.from_template_pack",
    "pdf.ai.rag.ingest",
    "pdf.ai.rag.query",
    "pdf.ai.rag.search",
    "pdf.ai.rag.cite_answer",
    "pdf.ai.rag.chat",
    "pdf.ai.rag.export_report",
    "pdf.ai.rag.highlight_sources",
}


@lru_cache(maxsize=1)
def load_tool_manifest() -> ToolManifest:
    manifest_path = _repo_root() / "schemas" / "tool-manifest.full.json"
    if manifest_path.exists():
        raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        tools = [_tool_spec_from_raw(item) for item in raw.get("tools", [])]
        return ToolManifest(
            manifest_version=str(raw.get("manifest_version", "0.1")),
            tools=tools,
        )
    return _fallback_manifest()


def list_tools() -> list[ToolSpec]:
    return load_tool_manifest().tools


def get_tool(name: str) -> ToolSpec:
    for tool in list_tools():
        if tool.name == name:
            return tool
    raise AgentPDFException("tool_not_implemented", f"Unknown tool: {name}")


def _tool_spec_from_raw(raw: dict[str, Any]) -> ToolSpec:
    name = str(raw["name"])
    return ToolSpec(
        name=name,
        status=raw["status"],
        description=raw["description"],
        category=raw.get("category"),
        interfaces=list(raw.get("interfaces", [])),
        input_schema=raw.get("input_schema"),
        output_schema=raw.get("output_schema"),
        implemented=name in IMPLEMENTED_TOOLS,
    )


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _fallback_manifest() -> ToolManifest:
    return ToolManifest(
        tools=[
            ToolSpec(
                name="agent.setup.claude_code",
                status="beta",
                description="Generate Claude Code MCP config for local AgentPDF tools.",
                category="agent",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.inspect.document",
                status="stable",
                description="Inspect a PDF document.",
                category="inspect",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.inspect.pages",
                status="stable",
                description="Inspect page-level geometry, text, image, and render facts.",
                category="inspect",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.plan",
                status="beta",
                description="Plan a local-first agent PDF workflow.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.run",
                status="beta",
                description="Execute a local-first agent PDF workflow manifest.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.workflow.report",
                status="beta",
                description="Summarize workflow artifacts, warnings, and validation.",
                category="workflow",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.context.build_packet",
                status="beta",
                description="Build a local Context Packet with source graph metadata.",
                category="context",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.compose.from_context",
                status="beta",
                description="Compose a validated target PDF from a Context Packet and target profile.",
                category="compose",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.target.profiles",
                status="beta",
                description="List built-in target PDF profiles with layout slots and accepted block types.",
                category="target",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.target.validate_profile",
                status="beta",
                description="Validate a built-in or custom target PDF profile for agent composition.",
                category="target",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.evidence.coverage_report",
                status="beta",
                description="Create an evidence coverage report from a composition artifact.",
                category="evidence",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.artifacts.export_bundle",
                status="beta",
                description="Export local PDFs, manifests, source maps, and reports as a portable audit bundle.",
                category="artifacts",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.artifacts.verify_bundle",
                status="beta",
                description="Verify a portable audit bundle manifest, ZIP entries, and SHA-256 checksums.",
                category="artifacts",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.plan",
                status="beta",
                description="Create a structured append-only patch manifest for Markdown, code, table, image, slide, source-map, and template-layer evidence.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.preview",
                status="beta",
                description="Preview patch effects and validation requirements.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.apply",
                status="beta",
                description="Apply a patch transaction and write a new PDF artifact.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.patch.verify",
                status="beta",
                description="Verify a patched PDF against a patch manifest.",
                category="patch",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.merge",
                status="stable",
                description="Merge multiple PDFs.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.split",
                status="stable",
                description="Split or extract selected PDF pages.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.extract_pages",
                status="stable",
                description="Extract specific pages into a new PDF.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.remove_pages",
                status="stable",
                description="Remove selected pages.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.rotate_pages",
                status="stable",
                description="Rotate selected pages.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.reorder_pages",
                status="stable",
                description="Reorder pages in a PDF.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.organize.insert_blank_pages",
                status="stable",
                description="Insert blank pages into a PDF.",
                category="organize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.optimize.compress",
                status="stable",
                description="Compress PDF content streams and report file-size savings.",
                category="optimize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.optimize.repair",
                status="beta",
                description="Rewrite a parseable PDF to rebuild output structure.",
                category="optimize",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.image_to_pdf",
                status="stable",
                description="Create a PDF from local image files.",
                category="convert_to_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.markdown_to_pdf",
                status="stable",
                description="Create a PDF from Markdown content.",
                category="convert_to_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.text_to_pdf",
                status="stable",
                description="Create a PDF from plain text content.",
                category="convert_to_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_images",
                status="stable",
                description="Render PDF pages to images.",
                category="convert",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.extract_images",
                status="stable",
                description="Extract embedded images from PDF pages.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_text",
                status="stable",
                description="Extract text from PDF pages.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_json",
                status="beta",
                description="Export local Document IR JSON from a PDF.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.convert.pdf_to_markdown",
                status="beta",
                description="Export cited Markdown from local Document IR.",
                category="convert_from_pdf",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.edit.watermark",
                status="stable",
                description="Add a text watermark overlay.",
                category="edit",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.edit.page_numbers",
                status="stable",
                description="Add page number overlays.",
                category="edit",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.metadata.read",
                status="stable",
                description="Read document metadata.",
                category="metadata",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.metadata.update",
                status="stable",
                description="Update document metadata.",
                category="metadata",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.metadata.remove",
                status="stable",
                description="Remove document metadata.",
                category="metadata",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.validation.validate_output",
                status="stable",
                description="Validate generated PDF output.",
                category="validation",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.validation.render_check",
                status="stable",
                description="Render selected pages in memory to verify output renderability.",
                category="validation",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.validation.blank_page_check",
                status="stable",
                description="Detect blank pages with text-layer and render evidence.",
                category="validation",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.parse.lite",
                status="beta",
                description="Parse PDF text layer into local Document IR.",
                category="ai_parse",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.from_prompt",
                status="beta",
                description="Create a validated local PDF from a prompt and template.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.template_preview",
                status="beta",
                description="Generate and validate a local preview PDF for a creation template.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.templates",
                status="beta",
                description="List local PDF creation templates, style packs, and color keys.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.template_packs",
                status="beta",
                description="List local template packs for agent-created PDFs.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.validate_template_pack",
                status="beta",
                description="Validate a local template pack contract.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.plan_template_pack",
                status="beta",
                description="Plan a local template-pack PDF creation call from target and context evidence.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.agent",
                status="beta",
                description="Run the local create agent: plan, create, render-check, blank-check, and coverage.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.create.from_template_pack",
                status="beta",
                description="Create a validated local PDF from a template pack with source and slot routing evidence.",
                category="ai_create",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.ingest",
                status="beta",
                description="Build a local cited keyword index from a PDF.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.query",
                status="beta",
                description="Query a local PDF index with extractive citations.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.search",
                status="beta",
                description="Search a local PDF index with cited chunks.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.cite_answer",
                status="beta",
                description="Find page and bbox citations that support an answer.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.chat",
                status="beta",
                description="Ask a local PDF and return answer, citations, report, and highlights.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.highlight_sources",
                status="beta",
                description="Create a highlighted source PDF from local RAG citations.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
            ToolSpec(
                name="pdf.ai.rag.export_report",
                status="beta",
                description="Create a cited PDF report from a local RAG answer.",
                category="ai_rag",
                interfaces=["cli", "mcp", "rest", "sdk"],
                implemented=True,
            ),
        ]
    )
